apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srv2
  template:
    metadata:
      labels:
        app: srv2
    spec:
      containers:
        - name: srv2
          image: srv02
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: srv2-service
spec:
  selector:
    app: srv2
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
