apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srv1
  template:
    metadata:
      labels:
        app: srv1
    spec:
      containers:
        - name: srv1
          image: srv01
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: srv1-service
spec:
  selector:
    app: srv1
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
